name: Force to Sync
on:
  workflow_dispatch:
jobs:
  sync-force:
    uses: WillBooster/reusable-workflows/.github/workflows/sync.yml@main
    with:
      sync_params_without_dest: '--force -v -i node_modules -i renovate.json'
    secrets:
      DEST_GIT_URL: git@github.com:WillBoosterLab/reusable-workflows.git
