name: Test

on:
  workflow_call:
    inputs:
      artifact_path:
        required: false
        type: string
      ci_label:
        default: medium
        required: false
        type: string
      custom_test_command:
        required: false
        type: string
      dot_env_path:
        default: .env
        required: false
        type: string
      environment:
        required: false
        type: string
      github_hosted_runner:
        required: false
        type: boolean
      paths_ignore:
        default: '["**.md", "**/docs/**"]'
        required: false
        type: string
      runs_on:
        required: false
        type: string
      target_organization:
        required: false
        type: string
      no_skip:
        required: false
        type: boolean
    secrets:
      DOT_ENV:
        required: false
      GH_TOKEN:
        required: true
      NPM_TOKEN:
        required: false
jobs:
  pre:
    # To avoid testing on synced (mirrored) repos.
    if: ${{ !startsWith(github.head_ref, 'refs/heads/renovate/') && github.head_ref != 'refs/heads/wbfy' && (!inputs.target_organization || github.repository_owner == inputs.target_organization) }}
    runs-on: ${{ (inputs.runs_on && fromJSON(inputs.runs_on)) || ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || fromJSON('["self-hosted", "medium"]') }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      # GitHub's Branch Protection and Rulesets require job running, so we should not skip entier jobs.
      - if: ${{ !inputs.no_skip }}
        id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: false
          skip_after_successful_duplicate: true
          paths_ignore: ${{ inputs.paths_ignore }}
  detect-node-version-matrix:
    needs: pre
    runs-on: ${{ (inputs.runs_on && fromJSON(inputs.runs_on)) || ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || fromJSON('["self-hosted", "medium"]') }}
    outputs:
      json: ${{ steps.detect-node-version-matrix.outputs.json }}
    steps:
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        uses: actions/checkout@v5
      # We need Node.js only if `grep -q nodejs .tool-versions && [[ ! -f .node-version ]]`
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        id: check-node
        run: |
          if ! grep -q "node" .tool-versions && [[ ! -f .node-version ]] && ([[ ! $(node --version) ]] || [[ ! $(npx --version) ]]); then
            echo "require-node-install=1" >> $GITHUB_OUTPUT
          fi
      - if: ${{ steps.check-node.outputs.require-node-install }}
        uses: actions/setup-node@v6
        with:
          check-latest: true
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        id: detect-node-version-matrix
        # We must use actions/setup-node if no Node.js description exists in .tool-versions and no .node-version exists
        run: |
          NODE_VERSIONS=""
          if ! grep -q "node" .tool-versions && [[ ! -f .node-version ]]; then
            CONSTRAINT=$(node -e "console.log(((require('./package.json') || {}).engines || {}).node)")
            NODE_VERSIONS=$(npx -y semver -r "$CONSTRAINT" 14.999.999 16.999.999 18.999.999 20.999.999 22.999.999 24.999.999 | xargs | sed 's/ /","/g' | sed 's/\.999\.999//g')
          fi
          echo "json=[\"$NODE_VERSIONS\"]" >> $GITHUB_OUTPUT
  test:
    needs: [pre, detect-node-version-matrix]
    runs-on: ${{ (inputs.runs_on && fromJSON(inputs.runs_on)) || ((!github.event.repository.private || inputs.github_hosted_runner) && 'ubuntu-latest') || fromJSON(format('["self-hosted", "{0}"]', inputs.ci_label)) }}
    env:
      FORCE_COLOR: 3
      NODE_OPTIONS: --max-old-space-size=4096
      # arguments
      HAS_DOT_ENV: ${{ !!secrets.DOT_ENV }}
      HAS_TEST_COMMAND: ${{ !!inputs.custom_test_command }}
      WB_ENV: ${{ inputs.environment || 'test' }}
    strategy:
      matrix:
        # c.f. https://github.community/t/reusable-workflow-with-strategy-matrix/205676
        node-version: ${{ fromJson(needs.detect-node-version-matrix.outputs.json || '[""]') }}
    steps:
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        uses: fkirc/skip-duplicate-actions@master
        with:
          cancel_others: true
          paths_ignore: ${{ inputs.paths_ignore }}
      - if: ${{ needs.pre.outputs.should_skip != 'true' && !github.event.repository.private }}
        uses: actions/checkout@v5
      - if: ${{ needs.pre.outputs.should_skip != 'true' && github.event.repository.private }}
        run: |
          if [[ ! -d .git ]]; then
            git init --initial-branch=main
          else
            rm -f .git/shallow.lock
          fi
          git remote add origin git@github.com:${{ github.repository }}.git || git remote set-url origin git@github.com:${{ github.repository }}.git
          git fetch --depth 1 origin ${{ github.head_ref || github.ref_name }}
          git stash --include-untracked || true
          git checkout -B ${{ github.head_ref || github.ref_name }} origin/${{ github.head_ref || github.ref_name }}
          git reset --hard origin/${{ github.head_ref || github.ref_name }}
      - if: ${{ needs.pre.outputs.should_skip != 'true' && env.HAS_DOT_ENV == 'true' }}
        run: echo '${{ secrets.DOT_ENV }}' > ${{ inputs.dot_env_path }}

      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Check version files
        id: check-ver
        run: |
          if [[ -f .tool-versions || -f .node-version || -f .python-version ]]; then
            echo "exist-any-version=1" >> $GITHUB_OUTPUT
          fi
          if [[ -f .node-version ]] || grep -q nodejs .tool-versions; then
            echo "exist-nodejs-version=1" >> $GITHUB_OUTPUT
          fi
      - if: ${{ needs.pre.outputs.should_skip != 'true' && !steps.check-ver.outputs.exist-nodejs-version }}
        uses: actions/setup-node@v6
        with:
          check-latest: true
          node-version: ${{ matrix.node-version || 22 }}
      - if: ${{ needs.pre.outputs.should_skip != 'true' && steps.check-ver.outputs.exist-any-version }}
        uses: willbooster/asdf-actions/install@main
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Show environment information
        id: env-info
        # https://stackoverflow.com/a/677212
        run: |
          echo "concurrency-group: ${{ github.workflow }}-${{ github.ref }}"
          echo "WB_ENV: $WB_ENV"
          echo "node: $(node -v)"
          echo "npm: $(npm -v)"
          if [[ -f bunfig.toml ]] && grep -q bun .tool-versions; then
            echo "bun: $(bun -v)"
            echo "runner=bun" >> $GITHUB_OUTPUT
          else
            YARN=$(yarn -v); echo "yarn: $YARN"
            if [[ "$YARN" == "1."* ]]; then
              echo "yarn-dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
            fi
            echo "runner=yarn" >> $GITHUB_OUTPUT
          fi

          if PYTHON=$(python --version 2> /dev/null); then echo "python: $PYTHON"; fi
          if POETRY=$(poetry --version 2> /dev/null); then
            echo "poetry: $POETRY"
            poetry config virtualenvs.in-project true
          fi

      - if: ${{ needs.pre.outputs.should_skip != 'true' && steps.env-info.outputs.yarn-dir }}
        uses: actions/cache@v4
        with:
          path: ${{ steps.env-info.outputs.yarn-dir }}
          # Don't use **/yarn.lock because it scans yarn.lock in node_modules
          # c.f. https://github.com/AllanChain/blog/issues/98
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1-

      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Install dependencies
        run: |
          if [[ "${{ steps.env-info.outputs.runner }}" == "bun" ]]; then
            bun update
          else
            ${{ steps.env-info.outputs.runner }} install --no-immutable || true # To ignore postinstall errors
          fi
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Run "common/ci-setup" npm script if exists
        run: if grep -q '"common/ci-setup":' package.json; then ${{ steps.env-info.outputs.runner }} run common/ci-setup; fi
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Run "test/ci-setup" npm script if exists
        run: if grep -q '"test/ci-setup":' package.json; then ${{ steps.env-info.outputs.runner }} run test/ci-setup; fi
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Run "typecheck" npm script if exists
        run: |
          if grep -q '"typecheck":' package.json; then
            # Deal with .next errors
            rm -Rf .next
            ${{ steps.env-info.outputs.runner }} run typecheck
          fi
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Fix code
        run: |
          if grep -q '"gen-code":' package.json; then
            ${{ steps.env-info.outputs.runner }} run gen-code
          fi
          if grep -q '"cleanup":' package.json; then
            ${{ steps.env-info.outputs.runner }} run cleanup
          elif grep -q '"lint-fix":' package.json; then
            ${{ steps.env-info.outputs.runner }} run lint-fix
          elif grep -q '"lint":' package.json; then
            ${{ steps.env-info.outputs.runner }} run lint
          fi
          if grep -q '"build/ci":' package.json; then
            ${{ steps.env-info.outputs.runner }} run build/ci
          elif grep -q '"build":' package.json; then
            ${{ steps.env-info.outputs.runner }} run build
          fi
          if git status | grep -q "Changes not staged for commit"; then
            git status
            git diff
            if [[ "${{ github.event.repository.private }}" == "true" ]]; then
              git add -A
              git commit -m "fix: apply changes of autofix workflow" --no-verify
              git push origin ${{ github.head_ref }} --no-verify
            else
              echo "Found changes during gen-code, cleanup, lint-fix and/or build"
              exit 1
            fi
          fi
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Test
        run: |
          if [[ "${{ env.HAS_TEST_COMMAND }}" == "true" ]]; then
            ${{ steps.env-info.outputs.runner }} run ${{ inputs.custom_test_command }}
          elif grep -q '"test/ci":' package.json; then
            ${{ steps.env-info.outputs.runner }} run test/ci
          elif grep -q '"test":' package.json; then
            ${{ steps.env-info.outputs.runner }} run test
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - if: ${{ needs.pre.outputs.should_skip != 'true' }}
        name: Run lint-staged
        run: |
          if grep -q '"lint-staged":' package.json; then
            for file in $(ls package.json packages/*/package.json); do
              sed -i -e 's/"name":/"name" :/' $file
              git add -A
            done
            ${{ steps.env-info.outputs.runner }} run lint-staged --allow-empty
          fi
      - if: ${{ needs.pre.outputs.should_skip != 'true' && env.GITHUB_TOKEN != '' && github.event_name == 'pull_request' }}
        name: Test release script
        run: |
          git switch -C $(jq -r ".branches[0]" .releaserc.json)
          if grep -q '"release-test":' package.json; then
            ${{ steps.env-info.outputs.runner }} run release-test
          else
            node node_modules/semantic-release/bin/semantic-release.js --dry-run
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - if: ${{ needs.pre.outputs.should_skip != 'true' && inputs.artifact_path }}
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: ${{ inputs.artifact_path }}

      - if: ${{ always() }}
        name: Clean up pyc files, docker and ports
        run: |
          : # pyc
          sudo rm -f **/*.pyc &
          : # Docker
          true $(docker rm -f $(docker ps -q) 2> /dev/null)
          true $(docker system prune -a -f --filter "until=4h")
          if [[ ! $(docker ps) ]]; then
            (which docker && sleep 5 && sudo reboot) &
          fi
          : # port
          npx --yes kill-port@latest 3000 > /dev/null &
