name: Merge wbfy
on:
  workflow_call:
    inputs:
      github_hosted_runner:
        required: false
        type: boolean
      target_organization:
        required: false
        type: string
    secrets:
      GH_TOKEN:
        required: true
jobs:
  wbfy-merge:
    if: ${{ !inputs.target_organization || github.repository_owner == inputs.target_organization }}
    # github.event.repository.private is always true if job is scheduled
    runs-on: ${{ (!github.event.repository.private && 'ubuntu-latest') || fromJSON('["self-hosted", "medium"]') }}
    env:
      FORCE_COLOR: 3
    steps:
      - name: Add Homebrew to PATH for Apple Silicon
        run: echo "/opt/homebrew/bin" >> $GITHUB_PATH

      # https://github.com/cli/cli/issues/8441#issuecomment-1870271857
      - name: Setup GitHub CLI
        run: |
          rm -Rf ~/.config/gh/* || true
          echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token
          gh auth setup-git

      - name: Decide action
        id: decide-action
        run: |
          if [[ -z $(git ls-remote https://github.com/${{ github.repository }} --heads wbfy) ]]; then
            echo "There is no wbfy branch."
            exit 0
          fi

          mkdir -p temp
          gh run list -R ${{ github.repository }} -b wbfy -L 10 -w Test --json conclusion,event > temp/wbfy.json

          cat > temp/wbfy.cjs << EOF
          const results = require('./wbfy.json');
          for (const result of results ?? []) {
            const { event, conclusion } = result;
            if (event !== 'push') continue;

            if (conclusion === 'success') {
              console.log('merge');
            } else if (conclusion === 'failure') {
              console.log('pr');
            }
            break;
          }
          EOF

          echo "action=$(node temp/wbfy.cjs)" >> $GITHUB_OUTPUT
          rm -Rf temp

      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        uses: actions/checkout@v4
        with:
          # Need histories to merge wbfy
          fetch-depth: 0
          # To trigger other workflows when running 'git push'
          token: ${{ secrets.GH_TOKEN }}
      - if: ${{ steps.decide-action.outputs.action == 'merge' }}
        # Unset core.hooksPath to disable husky
        run: |
          git config --global user.email "bot@willbooster.com"
          git config --global user.name "WillBooster Inc."
          : # Since wb-oracle-1 causes an error with exit code: 5
          git config --unset core.hooksPath || true
          git merge origin/wbfy --squash
          if git commit -m "chore: willboosterify this repo"; then
            git push origin ${{ github.event.repository.default_branch }}
          fi
          git push origin :wbfy
        env:
          HUSKY: 0

      - if: ${{ steps.decide-action.outputs.action == 'pr' }}
        run: |
          : # Since a duplicated PR is not allowed
          gh pr create -R ${{ github.repository }} --head wbfy --base main --title "chore: willboosterify this repo" --body "" || true

      - name: Clean up
        if: always()
        run: gh auth logout -h github.com
